version: '3'
services:
    client:
        build:
            context: ./client
        ports:
            - '3333:3000'
        depends_on:
            - server
        volumes:
            - ./client:/app/
            - /app/node_modules
        environment:
            - REACT_APP_API_SERVER_URL=${REACT_APP_API_SERVER_URL}
            - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
            - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
            - REACT_APP_AUTH0_CALLBACK_URL=${REACT_APP_AUTH0_CALLBACK_URL}
            - REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
            - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}
            - REACT_APP_CAPTCHA=${REACT_APP_CAPTCHA}
    server:
        build:
            context: ./server
        ports:
            - '5001:5000'
        depends_on:
            - db
        volumes:
            - ./server:/app
            - /app/node_modules
        environment:
            - PGDATABASE=${PGDATABASE}
            - PGHOST=${PGHOST}
            - PGPASSWORD=${PGPASSWORD}
            - PGUSER=${PGUSER}
            - ISSUER_BASE_URL=${ISSUER_BASE_URL}
            - AUDIENCE=${AUDIENCE}
            - API_KEY=${API_KEY}
    db:
        build:
            context: ./db
        volumes:
            - form-volume:/var/lib/postgresql/data
        ports:
            - '5433:5432'
        environment:
            - PGDATABASE=${PGDATABASE}
            - PGHOST=${PGHOST}
            - PGPASSWORD=${PGPASSWORD}
            - PGUSER=${PGUSER}
volumes:
    form-volume:
