version: '3'

services:
    client:
        build:
            context: ./client
        ports:
            - '3333:3000'
        depends_on:
            - server
        volumes:
            - ./client:/app/
            - /app/node_modules
            - ./client/.env.local:/app/.env.local
        environment:
            - FRONT=${{ secrets.FRONT }}

    server:
        build:
            context: ./server
        ports:
            - '5001:5000'
        depends_on:
            - db
        volumes:
            - ./server:/app
            - /app/node_modules
            - ./server/.env:/app/.env
        environment:
            - PGDATABASE=${PGDATABASE}
            - PGHOST=${PGHOST}
            - PGPASSWORD=${PGPASSWORD}
            - PGUSER=${PGUSER}
            - ISSUER_BASE_URL=${ISSUER_BASE_URL}
            - AUDIENCE=${AUDIENCE}
            - API_KEY=${API_KEY}

    db:
        build:
            context: ./db
        volumes:
            - form-volume:/var/lib/postgresql/data
        ports:
            - '5433:5432'
        environment:
            - PGDATABASE=${PGDATABASE}
            - PGHOST=${PGHOST}
            - PGPASSWORD=${PGPASSWORD}
            - PGUSER=${PGUSER}

volumes:
    form-volume:
